### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by aarongreenlee** [atom/release-notes#22]
1. I noticed the blue squirrel icon in the bottom right and wanted to see what package(s) were updated
2. I clicked the icon
3. Exception occurred

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.36.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes-view.js:108

TypeError: undefined is not a function
  at ReleaseNotesView.module.exports.ReleaseNotesView.fetchReleaseNotes (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes-view.js:108:41)
  at ReleaseNotesView.module.exports.ReleaseNotesView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes-view.js:98:12)
  at ReleaseNotesView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/node_modules/space-pen/lib/space-pen.js:178:25)
  at new ReleaseNotesView (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes-view.js:14:53)
  at createReleaseNotesView (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:16:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:47:18
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:476:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at WorkspaceView._results.push._this.(anonymous function) [as open] (/Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at HTMLSpanElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes-status-bar.js:33:35)
  at HTMLSpanElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLSpanElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLSpanElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```
{
  "release-notes": {
    "viewedVersion": "0.94.0"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.22.14
color-gutter, v0.3.1
go-plus, v3.0.10
grunt-runner, v0.6.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
Is this still happening on the latest Atom release, 0.166?

**Comment by erniebrodeur** [comment]
@kevinsawicki yes to both questions (same issue happening to me).

**Comment by kevinsawicki** [comment]
@erniebrodeur Can you check if `/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes` exists on disk?

**Comment by kevinsawicki** [comment]
And can you include the contents of that file if it does exist?

**Comment by erniebrodeur** [comment]
``` javascript
% cat /Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js
(function() {
  var $, convertMarkdown, createErrorNotes, createReleaseNotes, downloadReleaseNotes, saveReleaseNotes;

  $ = require('space-pen').$;

  module.exports = {
    fetch: function(version, callback) {
      return downloadReleaseNotes(version, callback);
    }
  };

  downloadReleaseNotes = function(version, callback) {
    return $.ajax({
      url: 'https://api.github.com/repos/atom/atom/releases',
      dataType: 'json',
      error: function() {
        var errorNotes;
        errorNotes = createErrorNotes(version);
        return typeof callback === "function" ? callback(errorNotes) : void 0;
      },
      success: function(releases) {
        return createReleaseNotes(version, releases, function(releaseNotes) {
          return typeof callback === "function" ? callback(releaseNotes) : void 0;
        });
      }
    });
  };

  createErrorNotes = function(version) {
    var errorNotes;
    errorNotes = [
      {
        version: version,
        notes: 'The release notes failed to download.',
        error: true
      }
    ];
    saveReleaseNotes(errorNotes);
    return errorNotes;
  };

  saveReleaseNotes = function(releaseNotes) {
    return localStorage.setItem('release-notes:releaseNotes', JSON.stringify(releaseNotes));
  };

  createReleaseNotes = function(version, releases, callback) {
    var releaseNotes;
    if (!Array.isArray(releases)) {
      releases = [];
    }
    version = version.replace(/-[a-fA-F0-9]{6}$/, '');
    while ((releases[0] != null) && releases[0].tag_name !== ("v" + version)) {
      releases.shift();
    }
    releaseNotes = releases.map(function(_arg) {
      var body, published_at, tag_name;
      body = _arg.body, published_at = _arg.published_at, tag_name = _arg.tag_name;
      return {
        date: published_at,
        notes: body,
        version: tag_name.substring(1)
      };
    });
    return convertMarkdown(releaseNotes, function() {
      saveReleaseNotes(releaseNotes);
      return callback(releaseNotes);
    });
  };

  convertMarkdown = function(releases, callback) {
    var convert, options, roaster;
    releases = releases.slice();
    roaster = require('roaster');
    options = {
      sanitize: true,
      breaks: true
    };
    convert = function(release) {
      if (release == null) {
        return callback();
      }
      return roaster(release.notes, options, (function(_this) {
        return function(error, html) {
          if (error == null) {
            release.notes = html;
          }
          return convert(releases.pop());
        };
      })(this));
    };
    return convert(releases.pop());
  };

}).call(this);
```

**Comment by erniebrodeur** [comment]
Hmmm, that may have been after a complete re-install to be honest.  I'm not experiencing it anymore and I'm up todate on all my versions, so sorry for the red herring (it did occur, and was so annoying I did a reinstall at like 3am, which worked).

**Comment by kevinsawicki** [comment]
Closing this out, I think this might have been local corruption issue that should not be present anymore not that asar is used for bundling all core files together.

Closing this out since it has not been reported again since the asar version shipped.
