### ISSUE TITLE
Error: The ::beforeRemove hook has been replaced by ::detached

### ISSUE THREAD

**Issue by sryze** [atom/release-notes#23]
When starting Atom:

```
Error: The ::beforeRemove hook has been replaced by ::detached. See https://github.com/atom/space-pen#attacheddetached-hooks for details.
  at ReleaseNotesStatusBar.View (/home/szx/.atom/packages/build/node_modules/space-pen/lib/space-pen.js:150:15)
  at new ReleaseNotesStatusBar (/opt/atom/resources/app/node_modules/release-notes/lib/release-notes-status-bar.js:14:58)
  at createStatusEntry (/opt/atom/resources/app/node_modules/release-notes/lib/main.js:63:18)
  at /opt/atom/resources/app/node_modules/release-notes/lib/main.js:70:22
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:382:27)
  at Atom.module.exports.Atom.startEditorWindow (/opt/atom/resources/app/src/atom.js:605:21)
  at Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///opt/atom/resources/app/static/index.js:59:25)
 index.js:73window.onload index.js:73
```

The error does not occur after I disable Release Notes in settings.

Atom version:  0.165.0
OS: Ubuntu 14.04 64-bit

**Comment by nathansobo** [comment]
Try deleting the package's `node_modules` and running `apm install`. I've released a new patch version of space-pen which should resolve the issue.

**Comment by sryze** [comment]
Seems working now, thanks. I removed release-note with `apm remove` and installed again.
