### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory /Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js 

### ISSUE THREAD

**Issue by scottswezey** [atom/release-notes#29]
[Enter steps to reproduce below:]

1. Open atom.app on OSX.
2. Select 'Restart and Install Update' from Apple Menu.
3. App restarts, begins to download another update, then shows crash dialog which created this issue.

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.48.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:14:15)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:70:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at convertMarkdown (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:73:15)
  at createReleaseNotes (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:64:12)
  at Object.$.ajax.success (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:22:16)
  at fire (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3206:7)
  at done (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8259:14)
  at XMLHttpRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8600:9)

```

### Commands

```
     -0:01.2 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment]
> Open atom.app on OSX.
> Select 'Restart and Install Update' from Apple Menu.
> App restarts, begins to download another update, then shows crash dialog which created this issue.

I just tried reproducing the issue by following the steps above, and wasn't able to. I downloaded [Atom 0.179.0](https://github.com/atom/atom/releases/tag/v0.179.0), started Atom, waited for the autoupdater to download the update, clicked 'Restart and Install Update', and Atom restarted without throwing an exception. 

@scottswezey Are you able to reliably reproduce this problem? If you have a bit of time to try upgrading again from 0.179.0 to 0.180.0 that would be great.

@kevinsawicki Do you see anything in that stack trace which might :point_right: to the problem here?

**Comment by scottswezey** [comment]
I am unable to reproduce.

**Comment by scottswezey** [comment]
@izuzak 

After reproducing this error, I found issue #30 as the Atom client seemed to think the issue had been reported and linked there. This issue and #30 may be related or duplicates.

As I can now reliably reproduce the error, I am posting new steps for you to try:

[Enter steps to reproduce below:]

1. Open atom.app 0.179.0 on OSX. Wait for the new version to finish downloading.
2. Select 'Restart and Install Update' from Apple Menu.
3. Manually open atom.app before it is reopened by the 'restart and install update' process.
4. Shortly after opening, the error should appear.


The steps above caused the old version (0.179.0) to load, and possibly caused a race condition between the app which I just opened, and the updater moving new files into place. As I'm not a fluent in working with node, I can't really dig into the source and attempt to verify this... but it may boil down to "impatient" users versus a lack of an update progress UI.

Please ping me if you need any further or information or have anything you would like me to test.

**Comment by scottswezey** [comment]
Haven't seen any further replies here, so I'm bumping in case the new information was overlooked.

@izuzak

**Comment by izuzak** [comment]
@scottswezey Sorry for not getting back to you sooner. I just tried reproducing this today by downloading 0.186.0 and making Atom auto-update to 0.187.0 and I didn't see the problem.

Can you still reproduce this with Atom 0.186.0? If so, could you record a GIF which demonstrates this, just to make sure I'm doing the same things as you are?

**Comment by scottswezey** [comment]
@izuzak I'll try to record it tonight. The key is to reopen atom before the auto update completes. The update dialog will have gone away, but it won't have automatically reopened yet.

**Comment by izuzak** [comment]
> The key is to reopen atom before the auto update completes. The update dialog will have gone away, but it won't have automatically reopened yet.

Yeah, that's what I was trying to do but couldn't trigger the exception. :confused:

**Comment by izuzak** [comment]
And thanks for the help!

**Comment by scottswezey** [comment]
Attempted to reproduce a few times, without success. Then just as I cancelled the recording, it happened... Of course, now it won't do it again.

On the bright side, it was happening consistently before, and now seems to be rare. If I can reproduce it in the current version after the next update, I'll update this issue.

**Comment by izuzak** [comment]
Ahh, okay, so it doesn't happen every time -- thanks. I'll tried doing it 2-3 times, I'll try a few more times.

**Comment by kevinsawicki** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
