### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

### ISSUE THREAD

**Issue by malawto** [atom/release-notes#30]
1. I opened a csharp class
2. I added a line, deleted it, then arrow key down several times to scroll the document.

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.48.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:14:15)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:70:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at convertMarkdown (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:73:15)
  at createReleaseNotes (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:64:12)
  at Object.$.ajax.success (/Applications/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:22:16)
  at fire (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3206:7)
  at done (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8259:14)
  at XMLHttpRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8600:9)

```

### Commands

```
     -0:06.4 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:04.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.8 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
 11x -0:02.4 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "release-notes": {
    "viewedVersion": "0.95.0"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus-async, v0.22.0
color-picker, v1.4.4
language-javascript-semantic, v0.1.0
omnisharp-atom, v0.1.6

# Dev
No dev packages
```

**Comment by malawto** [comment]
This is not an issue... Atom had not completed it's install and restart upon upgrading.  I restarted it and it's resolved.
