### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by dmaglio** [atom/release-notes#42]
**Atom Version**: 1.5.3
**System**: Unknown Windows Version
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.53.0
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /C:/Users/Davide%20Maglio/.atom/packages/release-notes/lib/release-notes-status-bar.coffee:4

TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/Davide Maglio/.atom/packages/release-notes/lib/release-notes-status-bar.coffee:1:1)
    at file:///C:/Users/Davide Maglio/.atom/packages/release-notes/lib/release-notes-status-bar.coffee:6:3
    at Object.<anonymous> (file:///C:/Users/Davide Maglio/.atom/packages/release-notes/lib/release-notes-status-bar.coffee:6:3)
    at Object.<anonymous> (file:///C:/Users/Davide Maglio/.atom/packages/release-notes/lib/release-notes-status-bar.coffee:1:1)
    at Module._compile (C:\Users\Davide Maglio\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Davide Maglio\AppData\Local\atom\app-1.5.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Davide Maglio\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.consumeStatusBar (file:///C:/Users/Davide Maglio/.atom/packages/release-notes/lib/main.coffee:54:28)
    at Provider.module.exports.Provider.provide (C:\Users\Davide Maglio\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\Davide Maglio\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-bootstrap3",
      "bootstrap-3-snippetset",
      "bootstrap3-snippets",
      "atom-beautify"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
ascii-codes, v0.3.3
auto-indent, v0.5.0
autocomplete-php, v0.3.7
color-picker, v2.1.1
file-icons, v1.6.14
flex-tool-bar, vundefined
jquery-snippets, v11.0.0
less-than-slash, v0.12.3
linter, v1.11.3
linter-bootlint, vundefined
linter-tidy, v2.1.0
release-notes, v0.53.0
sync-settings, v0.6.0
tool-bar, v0.2.0

# Dev
No dev packages
```

**Comment by winstliu** [comment]
Please uninstall the release-notes package (`apm uninstall release-notes`), as it has been archived and is no longer actively developed nor shipped with recent Atom versions.
